//! Signaling primitives for establishing WebRTC sessions over the
//! encrypted Qubee messaging channel. The signaling layer is
//! responsible for exchanging call invitations, SDP offers/answers
//! and ICE candidates between participants.
//!
//! [`CallManager`](crate::calling::call_manager::CallManager) depends
//! only on the [`SignalingTransport`] trait, so the concrete carrier
//! is pluggable. Two implementations live here: [`SignalingServer`],
//! an in‑memory loopback that routes messages between registered
//! clients without any network I/O (used by tests and local runs),
//! and [`ChannelSignalingTransport`], which serialises each message
//! and hands it to an outbound channel at the session boundary for the
//! encrypt‑and‑send layer to carry (see issue #67).

use anyhow::Result;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::{mpsc, RwLock};

use crate::calling::call_manager::{CallId, CallSettings, CallType};
use crate::calling::peer_connection::ICECandidate;
use crate::identity::identity_key::IdentityId;

/// High‑level signaling message exchanged between peers. Each
/// variant carries the metadata necessary for the recipient to act
/// upon the message. Messages are addressed to a specific identity
/// and routed by the [`SignalingServer`].
#[derive(Clone, Serialize, Deserialize, Debug)]
pub enum SignalingMessage {
    /// Invitation to join a call. Sent from the initiator to each
    /// participant. The recipient can either accept the invitation,
    /// triggering a WebRTC negotiation, or reject it.
    ///
    /// `media_root` is the 32-byte secret the caller mints for this
    /// call; both endpoints derive their media keys from it. It is only
    /// as confidential as the channel this frame rides — in Qubee that
    /// is the E2E-encrypted, authenticated 1:1 session, so no third
    /// party ever sees it.
    CallInvitation {
        call_id: CallId,
        caller: IdentityId,
        call_type: CallType,
        settings: CallSettings,
        media_root: [u8; 32],
    },
    /// An SDP offer generated by a peer. The recipient should set
    /// this as its remote description and respond with an answer.
    SdpOffer {
        call_id: CallId,
        sdp: String,
        sender: IdentityId,
    },
    /// An SDP answer generated in response to an offer. The sender
    /// that generated the offer should set this as its remote
    /// description.
    SdpAnswer {
        call_id: CallId,
        sdp: String,
        sender: IdentityId,
    },
    /// An ICE candidate discovered by the local peer. The recipient
    /// should add this candidate to its peer connection.
    IceCandidate {
        call_id: CallId,
        candidate: ICECandidate,
        sender: IdentityId,
    },
    /// Signal that a participant has hung up. The recipient should
    /// close its local peer connection and mark the call as ended.
    HangUp { call_id: CallId, sender: IdentityId },
}

/// In‑memory signaling server that routes messages between
/// registered clients. Each client registers with a unique
/// `IdentityId` and receives messages via an unbounded channel.
/// Clients can also send messages via the server to other
/// identities. This avoids requiring an external signalling service
/// for tests and local operation.
pub struct SignalingServer {
    clients: Arc<RwLock<HashMap<IdentityId, mpsc::UnboundedSender<SignalingMessage>>>>,
}

impl SignalingServer {
    /// Create a new empty signaling server. This should be called
    /// once at application startup.
    pub async fn new() -> Result<Self> {
        Ok(SignalingServer {
            clients: Arc::new(RwLock::new(HashMap::new())),
        })
    }

    /// Register a new client with the server. Returns a
    /// [`SignalingClient`] that can receive messages destined for
    /// `identity`. If another client is already registered with the
    /// same identity it will be replaced. Clients should call
    /// `register_client` before attempting to send or receive
    /// signaling messages.
    pub async fn register_client(&self, identity: IdentityId) -> SignalingClient {
        let (tx, rx) = mpsc::unbounded_channel();
        {
            let mut clients = self.clients.write().await;
            clients.insert(identity, tx);
        }
        SignalingClient {
            server: Arc::new(self.clone()),
            receiver: rx,
        }
    }

    /// Send a signaling message to the specified recipient. If the
    /// recipient is not currently registered, an error is returned.
    pub async fn send_message(
        &self,
        recipient: IdentityId,
        message: SignalingMessage,
    ) -> Result<()> {
        let clients = self.clients.read().await;
        if let Some(tx) = clients.get(&recipient) {
            tx.send(message)
                .map_err(|e| anyhow::anyhow!(e.to_string()))?
        } else {
            return Err(anyhow::anyhow!(
                "No signaling client registered for recipient"
            ));
        }
        Ok(())
    }
}

impl Clone for SignalingServer {
    fn clone(&self) -> Self {
        SignalingServer {
            clients: self.clients.clone(),
        }
    }
}

/// Carrier abstraction for outbound signaling. `CallManager` sends
/// every [`SignalingMessage`] through this trait and never names a
/// concrete transport, so the loopback [`SignalingServer`] (tests,
/// local runs) and the session-backed carrier (issue #67) are
/// interchangeable.
#[async_trait]
pub trait SignalingTransport: Send + Sync {
    /// Deliver `message` to `recipient`. Returns an error if the
    /// message cannot be handed off (e.g. no route to the recipient).
    async fn send(&self, recipient: IdentityId, message: SignalingMessage) -> Result<()>;
}

#[async_trait]
impl SignalingTransport for SignalingServer {
    async fn send(&self, recipient: IdentityId, message: SignalingMessage) -> Result<()> {
        self.send_message(recipient, message).await
    }
}

/// One serialised signaling payload addressed to a recipient identity,
/// handed off at the session boundary.
///
/// The encrypt-and-send layer (issue #67) drains these, encrypts
/// `payload` under the 1:1 session it holds for `recipient`, and
/// delivers it; the peer decrypts and feeds the bytes back through
/// [`SignalingMessage::from_bytes`].
#[derive(Clone, Debug)]
pub struct OutboundSignal {
    pub recipient: IdentityId,
    pub payload: Vec<u8>,
}

/// [`SignalingTransport`] that serialises each message and enqueues it
/// on an outbound channel. It stops at the session boundary on
/// purpose: it neither chooses a wire path nor encrypts — that is the
/// consumer's job (issue #67) — which keeps call logic independent of
/// how signaling is actually carried.
pub struct ChannelSignalingTransport {
    out: mpsc::UnboundedSender<OutboundSignal>,
}

impl ChannelSignalingTransport {
    /// Wrap an outbound sink. The receiving half is owned by the
    /// encrypt-and-send layer.
    pub fn new(out: mpsc::UnboundedSender<OutboundSignal>) -> Self {
        Self { out }
    }
}

#[async_trait]
impl SignalingTransport for ChannelSignalingTransport {
    async fn send(&self, recipient: IdentityId, message: SignalingMessage) -> Result<()> {
        let payload = message
            .to_bytes()
            .map_err(|e| anyhow::anyhow!("signaling encode failed: {e}"))?;
        self.out
            .send(OutboundSignal { recipient, payload })
            .map_err(|_| anyhow::anyhow!("signaling outbound channel closed"))?;
        Ok(())
    }
}

/// Client handle for receiving and sending signaling messages. Each
/// participant in a call holds a `SignalingClient` associated with
/// their `IdentityId`. The client can be used to await incoming
/// messages and to send messages via the server.
pub struct SignalingClient {
    server: Arc<SignalingServer>,
    receiver: mpsc::UnboundedReceiver<SignalingMessage>,
}

impl SignalingClient {
    /// Receive the next signaling message destined for this client.
    /// Returns `None` if the channel has been closed.
    pub async fn recv(&mut self) -> Option<SignalingMessage> {
        self.receiver.recv().await
    }

    /// Send a signaling message to another participant via the
    /// associated server. This is simply a convenience wrapper around
    /// [`SignalingServer::send_message`].
    pub async fn send_to(&self, recipient: IdentityId, message: SignalingMessage) -> Result<()> {
        self.server.send_message(recipient, message).await
    }
}

/// Backwards compatibility for the previous `CallSignal` type. The
/// older implementation serialised signalling messages directly as
/// bincode blobs. We retain the ability to serialise and
/// deserialise messages for transport over the encrypted chat layer.
impl SignalingMessage {
    /// Serializes the signal to bytes for encryption.
    pub fn to_bytes(&self) -> Result<Vec<u8>, bincode::Error> {
        bincode::serialize(self)
    }

    /// Tries to parse bytes into a `SignalingMessage`.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, bincode::Error> {
        bincode::deserialize(bytes)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_hangup(sender: IdentityId) -> SignalingMessage {
        SignalingMessage::HangUp {
            call_id: CallId::from([3u8; 16]),
            sender,
        }
    }

    #[tokio::test]
    async fn in_process_transport_routes_to_registered_client() {
        let server = SignalingServer::new().await.unwrap();
        let bob = IdentityId::from([2u8; 32]);
        let mut bob_inbox = server.register_client(bob).await;

        let transport: &dyn SignalingTransport = &server;
        transport
            .send(bob, sample_hangup(IdentityId::from([1u8; 32])))
            .await
            .unwrap();

        assert!(matches!(
            bob_inbox.recv().await,
            Some(SignalingMessage::HangUp { .. })
        ));
    }

    #[tokio::test]
    async fn in_process_transport_fails_for_unknown_recipient() {
        let server = SignalingServer::new().await.unwrap();
        let transport: &dyn SignalingTransport = &server;
        assert!(transport
            .send(
                IdentityId::from([9u8; 32]),
                sample_hangup(IdentityId::from([1u8; 32]))
            )
            .await
            .is_err());
    }

    #[tokio::test]
    async fn channel_transport_encodes_and_enqueues_round_trippable_bytes() {
        let (tx, mut rx) = mpsc::unbounded_channel();
        let transport = ChannelSignalingTransport::new(tx);
        let recipient = IdentityId::from([2u8; 32]);
        let sender = IdentityId::from([1u8; 32]);

        transport
            .send(recipient, sample_hangup(sender))
            .await
            .unwrap();

        let out = rx.recv().await.expect("payload enqueued");
        assert_eq!(out.recipient, recipient);
        // The consumer feeds these bytes straight back through from_bytes
        // after decrypting, so the round trip must hold.
        match SignalingMessage::from_bytes(&out.payload).unwrap() {
            SignalingMessage::HangUp { sender: s, .. } => assert_eq!(s, sender),
            other => panic!("unexpected variant: {other:?}"),
        }
    }

    #[tokio::test]
    async fn channel_transport_fails_closed_when_consumer_gone() {
        let (tx, rx) = mpsc::unbounded_channel();
        drop(rx);
        let transport = ChannelSignalingTransport::new(tx);
        assert!(transport
            .send(
                IdentityId::from([2u8; 32]),
                sample_hangup(IdentityId::from([1u8; 32]))
            )
            .await
            .is_err());
    }
}
